name: release

on: [workflow_dispatch]


jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3 # clone a repository
      - name: release
        run: npm install --save-dev semantic-release
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}